services:
  backend:
    image: ghcr.io/likeca/nextjs-django-backend:latest
    container_name: backend
    build:
      context: backend
    network_mode: host
    env_file:
      - backend/backend/settings/local.env
    restart: unless-stopped

  frontend:
    image: ghcr.io/likeca/nextjs-django-frontend:latest
    container_name: frontend
    build:
      context: frontend
    network_mode: host
    env_file:
      - frontend/.env
    depends_on:
      - backend
    restart: unless-stopped
