// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DiscoveryCategory struct {
	ID        string `db:"id"`
	Tab       string `db:"tab"`
	Icon      string `db:"icon"`
	Name      string `db:"name"`
	Sub       string `db:"sub"`
	SortOrder int32  `db:"sort_order"`
}

type DiscoveryEvent struct {
	ID             string      `db:"id"`
	City           string      `db:"city"`
	Name           string      `db:"name"`
	Detail         string      `db:"detail"`
	Meta           string      `db:"meta"`
	Icon           string      `db:"icon"`
	Image          *string     `db:"image"`
	ValidStartDate pgtype.Date `db:"valid_start_date"`
	ValidEndDate   pgtype.Date `db:"valid_end_date"`
	Lat            float64     `db:"lat"`
	Lng            float64     `db:"lng"`
	SortOrder      int32       `db:"sort_order"`
	CreatedAt      time.Time   `db:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at"`
}

type DiscoveryNews struct {
	ID             string      `db:"id"`
	City           string      `db:"city"`
	Name           string      `db:"name"`
	Detail         string      `db:"detail"`
	Meta           string      `db:"meta"`
	Icon           string      `db:"icon"`
	Image          *string     `db:"image"`
	ValidStartDate pgtype.Date `db:"valid_start_date"`
	ValidEndDate   pgtype.Date `db:"valid_end_date"`
	Lat            float64     `db:"lat"`
	Lng            float64     `db:"lng"`
	SortOrder      int32       `db:"sort_order"`
	CreatedAt      time.Time   `db:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at"`
}

type DiscoveryPromo struct {
	ID             string      `db:"id"`
	City           string      `db:"city"`
	Name           string      `db:"name"`
	Detail         string      `db:"detail"`
	Meta           string      `db:"meta"`
	Icon           string      `db:"icon"`
	Image          *string     `db:"image"`
	ValidStartDate pgtype.Date `db:"valid_start_date"`
	ValidEndDate   pgtype.Date `db:"valid_end_date"`
	Lat            float64     `db:"lat"`
	Lng            float64     `db:"lng"`
	SortOrder      int32       `db:"sort_order"`
	CreatedAt      time.Time   `db:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at"`
}

type DiscoveryThingToDo struct {
	ID             string      `db:"id"`
	City           string      `db:"city"`
	Name           string      `db:"name"`
	Detail         string      `db:"detail"`
	Meta           string      `db:"meta"`
	Icon           string      `db:"icon"`
	Image          *string     `db:"image"`
	ValidStartDate pgtype.Date `db:"valid_start_date"`
	ValidEndDate   pgtype.Date `db:"valid_end_date"`
	Lat            float64     `db:"lat"`
	Lng            float64     `db:"lng"`
	SortOrder      int32       `db:"sort_order"`
	CreatedAt      time.Time   `db:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at"`
}

type EmailChangeRequest struct {
	ID        string    `db:"id"`
	UserID    string    `db:"user_id"`
	NewEmail  string    `db:"new_email"`
	Token     string    `db:"token"`
	ExpiresAt time.Time `db:"expires_at"`
	CreatedAt time.Time `db:"created_at"`
}

type EmailOtp struct {
	ID        string    `db:"id"`
	Email     string    `db:"email"`
	Code      string    `db:"code"`
	Purpose   string    `db:"purpose"`
	ExpiresAt time.Time `db:"expires_at"`
	CreatedAt time.Time `db:"created_at"`
}

type MarketplaceCategory struct {
	ID        string `db:"id"`
	Icon      string `db:"icon"`
	Name      string `db:"name"`
	Sub       string `db:"sub"`
	SortOrder int32  `db:"sort_order"`
}

type MarketplaceJob struct {
	ID             string      `db:"id"`
	Title          string      `db:"title"`
	Description    string      `db:"description"`
	Category       string      `db:"category"`
	Area           string      `db:"area"`
	Budget         int32       `db:"budget"`
	Status         string      `db:"status"`
	PostedByID     pgtype.UUID `db:"posted_by_id"`
	ProviderID     pgtype.UUID `db:"provider_id"`
	ApplicantCount int32       `db:"applicant_count"`
	Note           string      `db:"note"`
	CreatedAt      time.Time   `db:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at"`
}

type MarketplaceJobApplication struct {
	ID         string    `db:"id"`
	JobID      string    `db:"job_id"`
	ProviderID string    `db:"provider_id"`
	Price      int32     `db:"price"`
	Message    string    `db:"message"`
	CreatedAt  time.Time `db:"created_at"`
	UpdatedAt  time.Time `db:"updated_at"`
}

type MarketplaceMessage struct {
	ID        string    `db:"id"`
	ThreadID  string    `db:"thread_id"`
	Sender    string    `db:"sender"`
	Text      string    `db:"text"`
	TimeLabel string    `db:"time_label"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type MarketplaceMessageThread struct {
	ID         string      `db:"id"`
	Slug       string      `db:"slug"`
	ProviderID string      `db:"provider_id"`
	UserID     pgtype.UUID `db:"user_id"`
	TimeLabel  string      `db:"time_label"`
	Unread     int32       `db:"unread"`
	CreatedAt  time.Time   `db:"created_at"`
	UpdatedAt  time.Time   `db:"updated_at"`
}

type MarketplaceProvider struct {
	ID         string      `db:"id"`
	Slug       string      `db:"slug"`
	Name       string      `db:"name"`
	Initials   string      `db:"initials"`
	Color      string      `db:"color"`
	Trade      string      `db:"trade"`
	City       string      `db:"city"`
	Rating     float64     `db:"rating"`
	JobsCount  int32       `db:"jobs_count"`
	DistanceKm int32       `db:"distance_km"`
	Lat        *float64    `db:"lat"`
	Lng        *float64    `db:"lng"`
	Years      int32       `db:"years"`
	Verified   bool        `db:"verified"`
	FromPrice  int32       `db:"from_price"`
	About      string      `db:"about"`
	UserID     pgtype.UUID `db:"user_id"`
	CreatedAt  time.Time   `db:"created_at"`
	UpdatedAt  time.Time   `db:"updated_at"`
}

type MarketplaceProviderReview struct {
	ID         string    `db:"id"`
	ProviderID string    `db:"provider_id"`
	Name       string    `db:"name"`
	Stars      int32     `db:"stars"`
	Text       string    `db:"text"`
	CreatedAt  time.Time `db:"created_at"`
	UpdatedAt  time.Time `db:"updated_at"`
}

type MarketplaceWalletTransaction struct {
	ID        string      `db:"id"`
	UserID    pgtype.UUID `db:"user_id"`
	Label     string      `db:"label"`
	DateLabel string      `db:"date_label"`
	Amount    int32       `db:"amount"`
	CreatedAt time.Time   `db:"created_at"`
	UpdatedAt time.Time   `db:"updated_at"`
}

type Payment struct {
	ID              string    `db:"id"`
	UserID          string    `db:"user_id"`
	StripePaymentID string    `db:"stripe_payment_id"`
	Amount          int32     `db:"amount"`
	Currency        string    `db:"currency"`
	Status          string    `db:"status"`
	Description     *string   `db:"description"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
}

type Permission struct {
	ID          string    `db:"id"`
	Name        string    `db:"name"`
	Description *string   `db:"description"`
	Resource    string    `db:"resource"`
	Action      string    `db:"action"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type Plan struct {
	ID              string    `db:"id"`
	Name            string    `db:"name"`
	Description     *string   `db:"description"`
	StripePriceID   string    `db:"stripe_price_id"`
	StripeProductID string    `db:"stripe_product_id"`
	Amount          int32     `db:"amount"`
	Currency        string    `db:"currency"`
	Interval        string    `db:"interval"`
	Features        []string  `db:"features"`
	IsPopular       bool      `db:"is_popular"`
	IsActive        bool      `db:"is_active"`
	CreatedAt       time.Time `db:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"`
}

type Role struct {
	ID          string    `db:"id"`
	Name        string    `db:"name"`
	Description *string   `db:"description"`
	IsSystem    bool      `db:"is_system"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type RolePermission struct {
	ID           string    `db:"id"`
	RoleID       string    `db:"role_id"`
	PermissionID string    `db:"permission_id"`
	CreatedAt    time.Time `db:"created_at"`
}

type Subscription struct {
	ID                   string    `db:"id"`
	UserID               string    `db:"user_id"`
	PlanID               string    `db:"plan_id"`
	StripeSubscriptionID string    `db:"stripe_subscription_id"`
	StripeCustomerID     string    `db:"stripe_customer_id"`
	Status               string    `db:"status"`
	CurrentPeriodStart   time.Time `db:"current_period_start"`
	CurrentPeriodEnd     time.Time `db:"current_period_end"`
	CancelAtPeriodEnd    bool      `db:"cancel_at_period_end"`
	CreatedAt            time.Time `db:"created_at"`
	UpdatedAt            time.Time `db:"updated_at"`
}

type TwoFactor struct {
	ID          string `db:"id"`
	UserID      string `db:"user_id"`
	Secret      string `db:"secret"`
	BackupCodes string `db:"backup_codes"`
	Confirmed   bool   `db:"confirmed"`
}

type User struct {
	ID               string             `db:"id"`
	Name             string             `db:"name"`
	Email            string             `db:"email"`
	Phone            *string            `db:"phone"`
	EmailVerified    bool               `db:"email_verified"`
	Image            *string            `db:"image"`
	IsAdmin          bool               `db:"is_admin"`
	RoleID           pgtype.UUID        `db:"role_id"`
	StripeCustomerID *string            `db:"stripe_customer_id"`
	TwoFactorEnabled bool               `db:"two_factor_enabled"`
	IsActive         bool               `db:"is_active"`
	IsSuperuser      bool               `db:"is_superuser"`
	IsStaff          bool               `db:"is_staff"`
	Password         string             `db:"password"`
	LastLogin        pgtype.Timestamptz `db:"last_login"`
	CreatedAt        time.Time          `db:"created_at"`
	UpdatedAt        time.Time          `db:"updated_at"`
}
