// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scratch.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const scratchInsertNullable = `-- name: ScratchInsertNullable :exec
INSERT INTO "user" (id, name, email, phone, role_id) VALUES ($1, $2, $3, $4, $5)
`

type ScratchInsertNullableParams struct {
	ID     string      `db:"id"`
	Name   string      `db:"name"`
	Email  string      `db:"email"`
	Phone  *string     `db:"phone"`
	RoleID pgtype.UUID `db:"role_id"`
}

func (q *Queries) ScratchInsertNullable(ctx context.Context, arg *ScratchInsertNullableParams) error {
	_, err := q.db.Exec(ctx, scratchInsertNullable,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.RoleID,
	)
	return err
}
