// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const userByEmail = `-- name: UserByEmail :one
SELECT u.id::text, u.name, u.email, u.email_verified, u.image, u.phone,
       u.is_admin, u.role_id, COALESCE(r.name, '') AS role_name, u.stripe_customer_id,
       u.two_factor_enabled, u.is_active, u.is_superuser, u.password, u.created_at, u.updated_at
FROM "user" u
LEFT JOIN role r ON r.id = u.role_id
WHERE LOWER(u.email) = LOWER($1)
`

type UserByEmailRow struct {
	UID              string      `db:"u_id"`
	Name             string      `db:"name"`
	Email            string      `db:"email"`
	EmailVerified    bool        `db:"email_verified"`
	Image            *string     `db:"image"`
	Phone            *string     `db:"phone"`
	IsAdmin          bool        `db:"is_admin"`
	RoleID           pgtype.UUID `db:"role_id"`
	RoleName         string      `db:"role_name"`
	StripeCustomerID *string     `db:"stripe_customer_id"`
	TwoFactorEnabled bool        `db:"two_factor_enabled"`
	IsActive         bool        `db:"is_active"`
	IsSuperuser      bool        `db:"is_superuser"`
	Password         string      `db:"password"`
	CreatedAt        time.Time   `db:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at"`
}

func (q *Queries) UserByEmail(ctx context.Context, lower string) (*UserByEmailRow, error) {
	row := q.db.QueryRow(ctx, userByEmail, lower)
	var i UserByEmailRow
	err := row.Scan(
		&i.UID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Phone,
		&i.IsAdmin,
		&i.RoleID,
		&i.RoleName,
		&i.StripeCustomerID,
		&i.TwoFactorEnabled,
		&i.IsActive,
		&i.IsSuperuser,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const userByID = `-- name: UserByID :one
SELECT u.id::text, u.name, u.email, u.email_verified, u.image, u.phone,
       u.is_admin, u.role_id, COALESCE(r.name, '') AS role_name, u.stripe_customer_id,
       u.two_factor_enabled, u.is_active, u.is_superuser, u.password, u.created_at, u.updated_at
FROM "user" u
LEFT JOIN role r ON r.id = u.role_id
WHERE u.id = $1
`

type UserByIDRow struct {
	UID              string      `db:"u_id"`
	Name             string      `db:"name"`
	Email            string      `db:"email"`
	EmailVerified    bool        `db:"email_verified"`
	Image            *string     `db:"image"`
	Phone            *string     `db:"phone"`
	IsAdmin          bool        `db:"is_admin"`
	RoleID           pgtype.UUID `db:"role_id"`
	RoleName         string      `db:"role_name"`
	StripeCustomerID *string     `db:"stripe_customer_id"`
	TwoFactorEnabled bool        `db:"two_factor_enabled"`
	IsActive         bool        `db:"is_active"`
	IsSuperuser      bool        `db:"is_superuser"`
	Password         string      `db:"password"`
	CreatedAt        time.Time   `db:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at"`
}

func (q *Queries) UserByID(ctx context.Context, id string) (*UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.UID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Phone,
		&i.IsAdmin,
		&i.RoleID,
		&i.RoleName,
		&i.StripeCustomerID,
		&i.TwoFactorEnabled,
		&i.IsActive,
		&i.IsSuperuser,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
